### GET ALL

GET http://localhost:4000/employees

### GET ALL IN COMPANY

PUT http://localhost:4000/employees/ZrWxXXhtXSAl76sNxup6

### POST ONE

POST http://localhost:4000/employees
Content-Type: application/json

{ "name": "Ylva Berglund" }

